name: ESLint check
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Init ESLint
        run: yarn run eslint --init
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsxhell
